In [3]:
import pandas as pd

In [5]:
data = {
    "Name": ["Sita", "Gita", "Raju", "Rani", "Amit", "Rahul", "Priya", "Kiran"],
    "Study_Hours": [2, 4, 1, 5, 3, 6, 4, 2],
    "Attendance": [70, 85, 60, 95, 80, 90, 88, 72],
    "Previous_Marks": [65, 75, 50, 90, 70, 92, 84, 68]
}

df = pd.DataFrame(data)

df

    Name  Study_Hours  Attendance  Previous_Marks
0   Sita            2          70              65
1   Gita            4          85              75
2   Raju            1          60              50
3   Rani            5          95              90
4   Amit            3          80              70
5  Rahul            6          90              92
6  Priya            4          88              84
7  Kiran            2          72              68

In [7]:
df.head()

   Name  Study_Hours  Attendance  Previous_Marks
0  Sita            2          70              65
1  Gita            4          85              75
2  Raju            1          60              50
3  Rani            5          95              90
4  Amit            3          80              70

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            8 non-null      str
 1   Study_Hours     8 non-null      int64
 2   Attendance      8 non-null      int64
 3   Previous_Marks  8 non-null      int64
dtypes: int64(3), str(1)
memory usage: 388.0 bytes

In [11]:
df.shape

(8, 4)

In [13]:
df.describe()

       Study_Hours  Attendance  Previous_Marks
count     8.000000     8.00000        8.000000
mean      3.375000    80.00000       74.250000
std       1.685018    11.82008       14.089003
min       1.000000    60.00000       50.000000
25%       2.000000    71.50000       67.250000
50%       3.500000    82.50000       72.500000
75%       4.250000    88.50000       85.500000
max       6.000000    95.00000       92.000000

In [15]:
average_study_hours = df["Study_Hours"].mean()

print("Average Study Hours:", average_study_hours)

Average Study Hours: 3.375

In [17]:
average_attendance = df["Attendance"].mean()

print("Average Attendance:", average_attendance)

Average Attendance: 80.0

In [19]:
average_marks = df["Previous_Marks"].mean()

print("Average Previous Marks:", average_marks)

Average Previous Marks: 74.25

In [21]:
highest_marks = df["Previous_Marks"].max()

print("Highest Previous Marks:", highest_marks)

Highest Previous Marks: 92

In [22]:
lowest_marks = df["Previous_Marks"].min()

print("Lowest Previous Marks:", lowest_marks)

Lowest Previous Marks: 50